backend:
  name: github
  repo: bramd/meanit.nl
  branch: main
  base_url: https://meanit-cms-auth.fly.dev
  auth_endpoint: /auth

media_folder: static/images
public_folder: /images

collections:
  - name: pages
    label: Pages
    files:
      - name: homepage-nl
        label: "Homepage (NL)"
        file: content/_index.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Full title, name: full_title, widget: boolean, default: true }
          - { label: Body, name: body, widget: markdown }
      - name: homepage-en
        label: "Homepage (EN)"
        file: content/_index.en.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Full title, name: full_title, widget: boolean, default: true }
          - { label: Body, name: body, widget: markdown }
      - name: about-nl
        label: "Over ons (NL)"
        file: content/over.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }
      - name: about-en
        label: "About us (EN)"
        file: content/over.en.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Body, name: body, widget: markdown }
      - name: contact-nl
        label: "Contact (NL)"
        file: content/contact.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }
      - name: contact-en
        label: "Contact (EN)"
        file: content/contact.en.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }
